# Generated by Django 5.2.5 on 2025-09-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='liked_ips',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
