# Generated by Django 5.2.5 on 2025-09-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_pageview_liked_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
