# Generated by Django 5.2.5 on 2025-09-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_pageview_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='pageview',
            name='ip_addresses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
