# Generated by Django 5.2.5 on 2025-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_pageview_ip_address_pageview_ip_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='read_time',
        ),
        migrations.AddField(
            model_name='pageview',
            name='read_times',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
