# Generated by Django 5.2.7 on 2025-10-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_blogpost_read_time_pageview_read_times'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogView',
        ),
    ]
