# Generated by Django 5.2.8 on 2025-11-09 10:59

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_blogview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
