# Generated by Django 5.2.7 on 2025-10-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_companyinfo_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client_name',
        ),
    ]
