# Generated by Django 5.2.7 on 2025-10-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_rename_name_client_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
