# Generated by Django 5.2.7 on 2025-10-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_client_client_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
    ]
