# Generated by Django 5.2.5 on 2025-08-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
