# Generated by Django 5.2.5 on 2025-08-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_varified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
