# Generated by Django 5.2.5 on 2025-09-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contact_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
