# Generated by Django 5.2.5 on 2025-09-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
