# Generated by Django 5.2.8 on 2025-11-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_is_2fa_enabled_profile_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
