"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from tkinter.ttk import Frame
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os


# ========================== Quick-start development settings - unsuitable for production =========================

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(%i)%y9ohy($_0e-=o&_eoj9e5kls4mc!!6x9t0p&reuy8xa(x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'jazzmin',  # <-- must be first
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'posts',
    'accounts',
    'invoices',
    'mathfilters',
    'corsheaders',
    'taggit',
    'django_summernote',
    'rest_framework',
    'rest_framework.authtoken',
    # 'two_factor',  # Uncomment if you want to use the full two-factor auth app
    # 'two_factor.plugins.phonenumber',  # If using SMS (optional) 
    # 'two_factor.plugins.email',  # If using email 2FA
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # MUST be at the top
    'django.middleware.security.SecurityMiddleware',
    'posts.middleware.APIKeyMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'
# Optional: session settings
SESSION_COOKIE_AGE = 60 * 60 * 24  # 1 day
SESSION_COOKIE_HTTPONLY = True       # Prevent JS access

# ============ Custom Setting ===========================================================================================

# CORS headers to allow external requests authentication
CUSTOM_CORS_ALLOW_HEADERS = [
    'x-api-key',
    'content-type',
    'x-csrftoken',
    'X-CSRF-Token',
    'X-csrf-token',
    'credentials'
]

CORS_ALLOW_HEADERS = list(default_headers) +  CUSTOM_CORS_ALLOW_HEADERS
# for only CSRF authentication
CORS_ALLOW_CREDENTIALS = True  # Essential for CSRF

# CSRF settings for trusted origins
# ------------------------------
# CORS Settings
# ------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    'https://onesane.vercel.app',
]

# Rest Framework configurations for OTP Catche
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "otp-cache",
    }
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# ------------------------------
# CSRF & Session Settings
# ------------------------------
# CORS 
CORS_ORIGIN_ALLOW_ALL = True
if DEBUG:
    # Local development
    CSRF_COOKIE_HTTPONLY = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False
else:
    # Production
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True

# ================ Custom Setting End =====================================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]



# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# ==================== Custom Settings ======================================================

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # Optional: for your project-level static files
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # For collected static files (production)

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Media files (User uploads, e.g., blog featured images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


# Email configurations : 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'hackingkali789@gmail.com'  # Replace with your email
EMAIL_HOST_PASSWORD = 'zoik tvac dvxi fwuq'  # Use an App Password (not your real password)
ADMIN_EMAIL = 'monusainideveloper@gmail.com'  # Where contact form messages are sent

# Default email sender
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Custom user model
AUTH_USER_MODEL = 'accounts.Profile'
# ==========================================================================

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

JAZZMIN_SETTINGS = {
    "site_title": "Onesane Admin",
    "site_header": "Onesane Admin Panel",
    "site_brand": "Onesane",
    "welcome_sign": "Welcome to the Onesane Admin Panel!",
    "copyright": "Onesane AI Solutions",
    "show_sidebar": True,
    "navigation_expanded": True,

    # ✅ This is correct location
    "user_avatar": "get_profile_image_url",  # ✅ THIS IS CORRECT
    "site_icon": "images/favicon.png",     # For browser tab
    "site_logo": "images/logo.png",        # For sidebar and top bar
    "site_logo_classes": "img-circle",     # Optional: makes it rounded

    # custom csss
    "custom_css": "css/custom.css",  # path is relative to /static/


    "icons": {
    # Accounts & Users
    "accounts.Profile": "fas fa-user-circle",       # Custom user model
    "accounts.Contact": "fas fa-envelope",          # Contacts
    "accounts.User": "fas fa-users",                # If separate model

    # Dashboard
    "dashboard.Dashboard": "fas fa-tachometer-alt", # Dashboard

    # Auth & Tokens
    "auth.Group": "fas fa-users-cog",               # Groups
    "authtoken.Token": "fas fa-key",                # Auth Token
    "rest_framework.authtoken.Token": "fas fa-user-lock", # DRF Token, if used

    # OTP Devices
    "otp_static.StaticDevice": "fas fa-mobile-alt", # Static devices
    "otp_totp.TOTPDevice": "fas fa-shield-alt",     # TOTP devices
    "otp.OtpStatic": "fas fa-lock",                 # If separate OTP model

    # Posts / Blog
    "posts.BlogPost": "fas fa-blog",
    "posts.Category": "fas fa-folder-open",
    "posts.Comment": "fas fa-comments",
    "posts.PageView": "fas fa-eye",

    # Tags
    "taggit.Tag": "fas fa-tags",                   # Tags

    # API Keys
    "posts.APIKey": "fas fa-key",  # DRF API keys
},

    # Theme
    "theme": "darkly",
}


LOGIN_URL = '/admin/login/'
